repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []
- repo: local
  hooks:
    - id: go-fmt
      name: Go fmt
      entry: go fmt ./...
      language: system
      pass_filenames: false
      types: [go]
    - id: go-vet
      name: Go vet
      entry: go vet ./...
      language: system
      pass_filenames: false
      types: [go]
    - id: go-mod-tidy
      name: Go mod tidy
      entry: sh -c 'go mod tidy && git add go.mod go.sum'
      language: system
      pass_filenames: false
      always_run: true
      files: \.(go|mod|sum)$
